Parallel test: failname

diff --git a/scripts/runtests.in b/scripts/runtests.in
--- a/scripts/runtests.in
+++ b/scripts/runtests.in
@@ -340,11 +340,17 @@ run_tests () {
         SHMERR=$(grep -c SHMERR < "$TMPDIR_PAR/testlog.txt")
         SUCC=$(grep -c SUCCESS < "$TMPDIR_PAR/testlog.txt")
         FAIL=$(grep -c FAILED < "$TMPDIR_PAR/testlog.txt")
+        FAIL_NAMES=$(grep FAILED < "$TMPDIR_PAR/testlog.txt" | sed 's/ FAILED$//')
         SKIP=$(grep -c SKIPPED < "$TMPDIR_PAR/testlog.txt")
+        rm -rf "$TMPDIR_PAR"
 
         echo "Runtest parallel: $ALL tests $NUM tests run, $SUCC successful, $FAIL failed, $SKIP skipped, $SHMERR shmem errors"
-
-        rm -rf "$TMPDIR_PAR"
+        if [ "$FAIL" -ne 0 ]; then
+            echo "Failed:"$'\n'"$FAIL_NAMES"
+            exit 1;
+        else
+            exit 0;
+        fi
     else
         while read -r testname; do
             run_one_test "$testname"
