Parallel test: Summary

diff --git a/scripts/runtests.in b/scripts/runtests.in
--- a/scripts/runtests.in
+++ b/scripts/runtests.in
@@ -207,6 +207,11 @@ TMPDIR=$(mktemp -d /tmp/runtest.XXXXXX)
 trap 'rm -rf "$TMPDIR"' 0 1 2 3 15
 
 run_one_test() {
+    if [ "$#" -ne 1 ]; then
+        echo "ERROR: run_one_test testfile"
+        return 1
+    fi
+    testname=$1
     testdir=$(dirname "$testname")
     # check if there's a "musthave" file with prerequisites from config.h
     if [ -e "$testdir/musthave" ] ; then
@@ -317,11 +322,28 @@ run_tests () {
         #Isolate: /tmp, $HOME, ipc, pid, net, proc
         #Withouth $HOME isolation, some tests fail. There are probably some files there which are used by tests.
         #linuxcnc source folder ($TOPDIR) isolation is not enought
-        #ToDo: Save and sumarize results
-        parallel -j "$PARALLEL" "echo job {%} {}; bwrap --dev-bind / / --overlay-src /tmp --tmp-overlay /tmp --overlay-src $HOME --tmp-overlay $HOME --unshare-ipc --unshare-pid --unshare-net --proc /proc --die-with-parent -- scripts/runtests -p {} ; echo done" < "$TMPDIR/alltests"
+        
+        TMPDIR_PAR=$(mktemp -d /tmp/runtest-parallel.XXXXXX) #Save and sumarize results in $TMPDIR_PAR/testlog.txt which is bound from outside
+
+        CMD="echo job {%} {}; bwrap --dev-bind / / \
+        --overlay-src /tmp --tmp-overlay /tmp \
+        --overlay-src $HOME --tmp-overlay $HOME \
+        --unshare-ipc --unshare-pid --unshare-net --proc /proc --die-with-parent -- scripts/runtests -p {}; echo done"
+        echo "$CMD"
+        parallel -j "$PARALLEL" "$CMD" < "$TMPDIR/alltests" 4> $TMPDIR_PAR/testlog.txt
+
+        #Quick and dirty sumary
+        ALL=$(cat $TMPDIR/alltests | wc -l)
+        NUM=$(cat $TMPDIR_PAR/testlog.txt | wc -l)
+        SHMERR=$(cat $TMPDIR_PAR/testlog.txt | grep SHMERR | wc -l)
+        SUCC=$(cat $TMPDIR_PAR/testlog.txt | grep SUCCESS | wc -l)
+        FAIL=$(cat $TMPDIR_PAR/testlog.txt | grep FAILED | wc -l)
+        SKIP=$(cat $TMPDIR_PAR/testlog.txt | grep SKIPPED | wc -l)
+
+        echo "Runtest Paralell: $ALL tests $NUM tests run, $SUCC successful, $FAIL failed, $SKIP skipped, $SHMERR shmem errors"
     else
         while read -r testname; do
-	    run_one_test
+            run_one_test "$testname"
         done < "$TMPDIR/alltests"
         SUCC=$((NUM-FAIL))
         echo "Runtest: $NUM tests run, $SUCC successful, $FAIL failed, $SKIP skipped, $SHMERR shmem errors"
@@ -398,5 +420,26 @@ fi
 if [ $CLEAN_ONLY -eq 1 ]; then
     clean "$@"
 else
-    run_tests "$@"
+    if [ "$#" -eq 1 ] && [ -f "$1" ]; then #Only one test with script as argument, assuming call from parallel
+        run_one_test "$1"
+        SUCC=$((NUM-FAIL))
+        echo "Runtest: $NUM tests run, $SUCC successful, $FAIL failed, $SKIP skipped, $SHMERR shmem errors"
+        #FD 4 is used in parallel to log test results, so stdout / stderr / fd 3 used above don't interfere
+        echo -n "$1" >&4
+        if [ "$SHMERR" -ne 0 ]; then
+            echo " SHMERR" >&4
+        fi
+        if [ "$FAIL" -ne 0 ]; then
+            echo " FAILED" >&4
+            exit 1;
+        elif [ "$SKIP" -ne 0 ]; then
+            echo " SKIPPED" >&4
+            exit 0;
+        else
+            echo " SUCCESS" >&4
+            exit 0;
+        fi
+    else
+        run_tests "$@"
+    fi
 fi
